export const CUJ_HOTSPOTS = [
  // 🏫 In-Campus
  "Main Gate",
  "Bus stop (outside the main gate)",
  "Bus stop (in front of DDE)",
  "DDE building",
  "DDE Badminton court",
  "Registrar office",
  "Tunnel",
  "Water tank above tunnel",
  "Sports ground",
  "Canteen",
  "Tapri",
  "Academic block",
  "VC ki kothi",
  "P.Fab building",
  "SPM Boys Hostel",
  "PMM building",
  "SPM Badminton court",
  "SPM Gym",
  "ISRO building",
  "Science block",
  "DRDO",
  "Professor's Quarters",
  "Girls Hostel",
  "Brigadier Rajinder Singh Auditorium",
  "DDE Library",
  "Central Library (under construction)",
  "Abhinav Teela",
  "Baba Surgal Dev Mandir",
  "Masjid (near CUJ village)",

  // 🏠 Outside-Campus
  "Panini Boys Hostel (Baribrahmna)",
  "Sainik Colony Boys Hostel",
  "Vivekanand Boys Hostel",
  "Funky Town",
  "Sewa Restaurant",
  "Back Banchers",
  "Rahya Chowk",
  "Rahya Morh",
  "Rahya Morh Bus Stop"
]; 